version: "3.8"

services:

  openhab:
    image: "openhab/openhab"
    depends_on:
      - "mosquitto"
    networks:
      - "realworld"
    ports:
      - "8080:8080"
      - "8101:8101"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/opt/openhab/addons:/openhab/addons"
      - "/opt/openhab/conf:/openhab/conf"
      - "/opt/openhab/userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=America/Bahia"
      USER_ID: 1000
      GROUP_ID: 1000
      
  mosquitto:
    image: "eclipse-mosquitto"
    networks:
      - "realworld"
    ports:
      - "1883:1883"
    volumes:
      - "mosquitto-config:/mosquitto/config"
      - "mosquitto-log:/mosquitto/log"
      
  config-editor:
    image: "linuxserver/code-server"
    networks:
      - "realworld"
    ports:
      - "8443:8443"
    environment:
      - "PUID=1000"
      - "GUID=1000"
      - "TZ=America/Bahia"
      - "FILE__PASSWORD=/run/secrets/code-server-passwd"
    volumes:
      - "code-server-config:/config"
      - "mosquitto-config:/mosquitto/config"
      - "mosquitto-log:/mosquitto/log"
      - "/opt/openhab/conf:/openhab/conf"
      - "/opt/openhab/userdata:/openhab/userdata"
    secrets:
      - "code-server-passwd"

volumes:
  mosquitto-config:
  mosquitto-log:
  code-server-config:

networks:
  frontend:
    driver: "bridge"

secrets:
  code-server-passwd: 
    external: true
